---

- hosts: webservers
  remote_user: root

  tasks:
  - name: Install Apache webserver
    yum:
      name: httpd
      state: latest
    
  - name: Install PHP
    yum:
      name: php
      state: latest
    notify:
    - restart apache
  - name: Start apache
    service:
      name: httpd
      state: started
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted

...